name: backend
description: A sample Functions Framework project for handling JSON.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

scripts:
  up: docker-compose up
  up_build: docker-compose build & docker-compose up

dependencies:
  dio: ^3.0.10
  path: ^1.7.0
  uuid: ^2.2.2
  functions_framework: ^0.3.0
  shelf: ^0.7.9
  shelf_router: ^0.7.4
  kiwi: ^2.1.1
  shelf_static: ^0.2.9+2

dev_dependencies:
  shelf_router_generator: ^0.7.0+1
  build_runner: ^1.10.2
  functions_framework_builder: ^0.3.0
  http: ^0.12.0
  json_serializable: ^3.5.1
  test: ^1.15.0
  test_process: ^1.0.0
