name: backend
description: A sample Functions Framework project for handling JSON.
# version: 0.1.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: ">=2.10.0 <3.0.0"

scripts:
  up: docker-compose up
  up_build: docker-compose build & docker-compose up

dependencies:
  dio: ^5.0.3
  path: ^1.7.0
  uuid: ^3.0.7
  functions_framework: ^0.4.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  kiwi: ^4.1.0
  shelf_static: ^1.1.1

dev_dependencies:
  shelf_router_generator: ^1.0.5
  build_runner: ^2.3.3
  functions_framework_builder: ^0.4.7
  http: ^0.13.5
  json_serializable: ^6.6.1
  test: ^1.23.1
  test_process: ^2.0.3
